apiVersion: apps/v1
kind: Deployment
metadata:
  name: tamvn-capstone-deployment
  labels:
    app: tamvn-capstone-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: tamvn-capstone-app
  template:
    metadata:
      labels:
        app: tamvn-capstone-app
    spec:
      containers:
        - name: tamvn-capstone-app
          image: tamvn/tamvn-capstone
          ports:
            - containerPort: 80
