apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMvakNDQWVhZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJek1EVXhNekV6TkRneU5sb1hEVE16TURVeE1ERXpORGd5Tmxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBT2UrCnRKUVlsSGNER0g3eXR6cFcxSlJTRXptRG5sc1dDeC9yU3NhRmE3WldSY0dIcXNPcDZGS3RSbk5ya1R1ZEV3WUIKQkw4ZWdaa0dSVERFVEU3eHhqQnVZV29wUE50cWh4c3ZvWE94RDUrcnFpa21DOWg3VUhhS04zc0tJcGlxek1xMQpZWTlLVmdBanNnM2hXUDhqWnM2QUZtdDJFYkJSeWp0VzR2RnY0dGh3QWNLL1pYWmtUUWorUWdRcHU4aHlwalcrCnNZSERVclkxQ1hPRk9wK0hoaHFYQXFTWG1TdCtFYlQyQTZWcVZxNTdrYW43ZkFGNTFma08wVXVPM28rZ25YUnIKVlZKMEJ3N1BzdDVxZG1wVmVzNFhPV3VtdDRuNjhCS1NsRFVTY3Y4bFp6QlZlalVtVVBscjNFWkNEQVp0VmFwLwp0SExBNFd1MGpBRkNPK2hpdkRFQ0F3RUFBYU5aTUZjd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZCNEc1OUhZQ3RRTVlIZi9tUHhsYVJjR0xBL1FNQlVHQTFVZEVRUU8KTUF5Q0NtdDFZbVZ5Ym1WMFpYTXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBRDhvbmdHQXJCYVo1dG5selVsVwp1eEp2dEJKM3FmVHpPczRTS1FxZWMzS1hDa3NWbzRITThnSDdYZjBVZk9XWDhtM1hmek9TcnFHdC9lQU9sS080CnF3dHNLc3MrK081d1VUc1AydU5mSDlHaFJGYldEbEZvdXd5Znptam5raGNiRUFQdHFxRlhRNEw0MTgzZ2w4cG4KczBmV2djRXcxOXNFN2Y0SG9zSU5pcmgvYmVwU0JQa3V2cU1yTVRPSThYK3F1RmNROGdiUXJTZGJac3IrTmJpQgoxTnV1K3cwdGxqMEZheGZvUGVVZTlUVThRNnNqTEdGNHRDTmduL3FRbGdrMEU4VE0ydTJXYm92R2txNHVtZ2diClBlVDMzdFZGQTRsOTkrQmxoS2hDK0RPelJtNTFOTCtmKzZML1RrZXIrTDVkeHhCcnFmOG1nNjFYNDBGdGhBUUEKcU9RPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://5B805697390CCE6E80938C0C495CBBA1.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:646195298411:cluster/tamvn-capstone-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:646195298411:cluster/tamvn-capstone-cluster
    user: arn:aws:eks:us-east-1:646195298411:cluster/tamvn-capstone-cluster
  name: arn:aws:eks:us-east-1:646195298411:cluster/tamvn-capstone-cluster
current-context: arn:aws:eks:us-east-1:646195298411:cluster/tamvn-capstone-cluster
kind: Service
metadata:
  name: tamvn-capstone-service
spec:
  type: LoadBalancer
  selector:
    app: tamvn-capstone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
