apiVersion: v1
kind: Service
metadata:
  name: tamvn-capstone-service
spec:
  type: LoadBalancer
  selector:
    app: tamvn-capstone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
